apiVersion: v2
name: metabase
description: Metabase analytics and dashboard platform
type: application
version: 1.0.0
appVersion: "0.48.0"
maintainers:
  - name: Vijay Chhatbar
    email: vijay@chhatbar.net