apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: dagster-home
  namespace: {{ .Release.Namespace }}
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: local-nvme
  resources:
    requests:
      storage: 10Gi
