apiVersion: v1
kind: Service
metadata:
  name: schema-registry-svc
  namespace: {{ .Release.Namespace }}
  labels:
    app: schema-registry
spec:
  ports:
    - port: 8081
      name: http
  selector:
    app: schema-registry
  type: ClusterIP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: schema-registry
  namespace: {{ .Release.Namespace }}
  labels:
    app: schema-registry
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: schema-registry
  template:
    metadata:
      labels:
        app: schema-registry
    spec:
      containers:
        - name: schema-registry
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: 8081
          env:
            - name: SCHEMA_REGISTRY_HOST_NAME
              value: schema-registry
            - name: SCHEMA_REGISTRY_LISTENERS
              value: "http://0.0.0.0:8081"
            - name: SCHEMA_REGISTRY_KAFKASTORE_BOOTSTRAP_SERVERS
              value: {{ .Values.kafkaBootstrapServers | quote }}
            - name: SCHEMA_REGISTRY_KAFKASTORE_TOPIC_REPLICATION_FACTOR
              value: "3"
          {{- with .Values.resources }}
          resources:
            {{- toYaml . | nindent 12 }}
          {{- end }}
