apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "opensky-producer.fullname" . }}-config
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "opensky-producer.labels" . | nindent 4 }}
data:
  {{- range $key, $value := .Values.config }}
  {{ $key }}: "{{ $value }}"
  {{- end }}
