apiVersion: v1
kind: Secret
metadata:
  name: {{ include "opensky-producer.fullname" . }}-secrets
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "opensky-producer.labels" . | nindent 4 }}
type: Opaque
stringData:
  {{- range $key, $value := .Values.secrets }}
  {{ $key }}: {{ $value | quote }}
  {{- end }}
