apiVersion: v2
name: dagster
description: Dagster pipeline orchestration platform
type: application
version: 1.0.0
appVersion: "1.5.12"
maintainers:
  - name: Vijay Chhatbar
    email: vijay@chhatbar.net